CREATE TABLE hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(100) NOT NULL,
    stars INTEGER NOT NULL,

    CONSTRAINT chk_hotels_name_not_blank
        CHECK (TRIM(name) <> ''),

    CONSTRAINT chk_hotels_city_not_blank
        CHECK (TRIM(city) <> ''),

    CONSTRAINT chk_hotels_stars
        CHECK (stars BETWEEN 1 AND 5)
);


CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,

    CONSTRAINT chk_customers_first_name_not_blank
       CHECK (TRIM(first_name) <> ''),

    CONSTRAINT chk_customers_last_name_not_blank
       CHECK (TRIM(last_name) <> ''),

    CONSTRAINT chk_customers_email_not_blank
       CHECK (TRIM(email) <> '')
);


CREATE UNIQUE INDEX ux_customers_email_lower
    ON customers (LOWER(email));


CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_reservations_hotel
      FOREIGN KEY (hotel_id)
          REFERENCES hotels (id)
          ON DELETE RESTRICT,

    CONSTRAINT fk_reservations_customer
      FOREIGN KEY (customer_id)
          REFERENCES customers (id)
          ON DELETE RESTRICT,

    CONSTRAINT chk_reservations_dates
      CHECK (check_out > check_in),

    CONSTRAINT chk_reservations_total_price
      CHECK (total_price >= 0),

    CONSTRAINT chk_reservations_status
      CHECK (status IN ('ACTIVE', 'CANCELLED'))
);


CREATE INDEX idx_reservations_hotel_id
    ON reservations (hotel_id);


CREATE INDEX idx_reservations_customer_id
    ON reservations (customer_id);


CREATE INDEX idx_reservations_status
    ON reservations (status);


CREATE INDEX idx_reservations_check_in
    ON reservations (check_in);


CREATE INDEX idx_reservations_check_out
    ON reservations (check_out);


CREATE INDEX idx_hotels_name
    ON hotels (name);


CREATE INDEX idx_hotels_city
    ON hotels (city);